services:
  api:
    container_name: auth
    build:
      context: ./Api/Auth
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnectionString=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  migrations:
    container_name: auth-migrations
    build:
      context: ./Api/Auth
      dockerfile: Dockerfile.migrations
    environment:
       - ConnectionStrings__DatabaseConnectionString=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    command: ["dotnet", "ef", "database", "update"]

  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
     - "5432:5432"
    
volumes:
 postgres_data: