// ┌─────────────────────────────────────────────────────────────────────────┐
// │  Contract tests – Gateway service                                       │
// │                                                                         │
// │  Gateway has two contract responsibilities:                             │
// │                                                                         │
// │  1. Kafka PRODUCER contract (fan-out)                                   │
// │     Gateway publishes IotSnapshotMessage to "iot.snapshots".            │
// │     Consumers: Notification service, HistoryStore (Node.js).            │
// │     Tool: PactNet message pacts (provider side)                         │
// │                                                                         │
// │  2. GraphQL API contract (HTTP)                                         │
// │     The React frontend depends on the { iot { devices { ... } } }       │
// │     query shape. Breaking schema changes must be detected early.        │
// │     Tool: HotChocolate schema export + snapshot comparison              │
// │                                                                         │
// │  Required packages to add when implementing:                            │
// │    PactNet                                                              │
// │    PactNet.Output.Xunit                                                 │
// └─────────────────────────────────────────────────────────────────────────┘

namespace GatewayTests.Contract;

// ----- Planned test cases ---------------------------------------------------
//
// Kafka producer verification (Gateway acts as PRODUCER):
//
//   [Fact] Gateway_SatisfiesIotSnapshotContract_ForNotificationConsumer
//     Load pact file generated by NotificationTests.Contract
//     Run PactVerifier: produce an IotSnapshotMessage via GatewayFactory
//     Assert Gateway's output satisfies the Notification consumer's pact
//
//   [Fact] Gateway_SatisfiesIotSnapshotContract_ForHistoryStoreConsumer
//     Load pact file generated by HistoryStore consumer test (Node.js / @pact-foundation/pact)
//     Assert Gateway's output satisfies the HistoryStore consumer's pact
//
// GraphQL schema contract:
//
//   [Fact] GraphQL_Schema_HasNotChangedFromSnapshot
//     Export SDL from the HotChocolate schema at startup
//     Compare to a committed schema snapshot file
//     Fail if they differ — forces intentional schema version bumps
//     (Schema snapshot lives at: Tests/GatewayTests/Contract/schema.graphql)
//
// ---------------------------------------------------------------------------
//
// IotSnapshotMessage published shape (must match Notification's IotSnapshotMessage):
//   {
//     "capturedAt": <ISO-8601>,
//     "devices": [
//       {
//         "type":    <string>,
//         "name":    <string>,
//         "payload": {
//           "co2":      <int?>,
//           "pm25":     <int?>,
//           "humidity": <int?>,
//           "energy":   <double?>
//         }
//       }
//     ]
//   }
//
// NOTE: Gateway uses int? for payload fields; Notification uses double?.
// This mismatch should be resolved before implementing CDC tests — both sides
// need to agree on the numeric type in the contract.
//
// ---------------------------------------------------------------------------

public sealed class GatewayContractTests
{
    // Placeholder — implement contracts listed above.
}
