FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /src

RUN dotnet tool install --global dotnet-ef
ENV PATH="/root/.dotnet/tools:${PATH}"

COPY Shared/CashFlow.Shared.csproj Shared/
COPY Auth/Auth.csproj Auth/
RUN dotnet restore Auth/Auth.csproj

COPY Shared/ Shared/
COPY Auth/ Auth/

WORKDIR /src/Auth
RUN dotnet build

CMD ["dotnet", "ef", "database", "update"]
