FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

RUN dotnet tool install --global dotnet-ef
ENV PATH="/root/.dotnet/tools:${PATH}"

COPY . .

RUN dotnet restore

RUN dotnet build

CMD ["sh", "-c", "dotnet-ef database update"]