// ┌─────────────────────────────────────────────────────────────────────────┐
// │  Contract tests – Auth service                                          │
// │                                                                         │
// │  Auth has two kinds of contracts:                                       │
// │                                                                         │
// │  1. REST API contract (HTTP)                                            │
// │     Other services (Gateway, React frontend) depend on:                 │
// │       POST /auth/register → 200 + Set-Cookie: GuardPass                │
// │       POST /auth/login    → 200 + Set-Cookie: GuardPass  |  401        │
// │     Tool: Pact HTTP provider verification                               │
// │                                                                         │
// │  2. JWT token contract (shared schema)                                  │
// │     Gateway validates JWTs issued by Auth. The token must contain:      │
// │       - claim "userId" (Guid)                                           │
// │       - valid RSA-SHA256 signature                                      │
// │       - issuer / audience matching configuration                        │
// │     This is verified via Gateway's JWT validation settings,             │
// │     not a separate Pact interaction.                                    │
// │                                                                         │
// │  Required packages to add when implementing:                            │
// │    PactNet                                                              │
// │    PactNet.Output.Xunit                                                 │
// └─────────────────────────────────────────────────────────────────────────┘

namespace AuthTests.Contract;

// ----- Planned test cases ---------------------------------------------------
//
// Provider-side verification (Auth acts as PROVIDER):
//
//   [Fact] Auth_SatisfiesRegisterContractFor_WebFrontend
//     Load pact file generated by the React frontend consumer test
//     Spin up Auth with WebApplicationFactory + Testcontainers Postgres
//     Run PactVerifier against POST /auth/register interaction
//
//   [Fact] Auth_SatisfiesLoginContractFor_WebFrontend
//     Same setup, verify POST /auth/login interactions:
//       - successful login → 200 + cookie
//       - failed login     → 401
//
// JWT schema test (no Pact needed – just a unit-level assertion):
//
//   [Fact] JwtProvider_GeneratedToken_ContainsUserIdClaim
//     Generate a token for a test user with a known GUID
//     Decode without signature validation
//     Assert "userId" claim equals the user's Guid string
//
//   [Fact] JwtProvider_GeneratedToken_HasCorrectIssuerAndAudience
//     Generate a token with configured issuer/audience
//     Assert token.Issuer and token.Audiences match JwtOptions
//
// ---------------------------------------------------------------------------

public sealed class AuthContractTests
{
    // Placeholder — implement contracts listed above.
}
